# Site settings
title: Single-Serving Photo
email: aaron@singleservingphoto.com
description: > # this means to ignore newlines until "baseurl:"
  This is where Aaron Bieber writes about photography.
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://www.singleservingphoto.com" # the base hostname & protocol for your site
twitter_username: aaronbieberpics
instagram_username: aaronbieber
facebook_page_name: aaronbiebergallery
excerpt_separator: ~~MORE~~
paginate: 5
highlighter: rouge
exclude: [vendor]

collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "default"
      author: Aaron Bieber
  - scope:
      path: ""
      type: "authors"
    values:
      permalink: "/authors/:title"
      layout: author
      twitter:
      instagram:

# Build settings
markdown: redcarpet
redcarpet:
  extensions:
    - no_intra_emphasis
    - fenced_code_blocks
    - autolink
    - tables
    - with_toc_data
    - smart
    - underline

plugins:
  - rouge
  - jekyll-compass
  - jekyll-paginate

sass:
  load_paths:
    - "./vendor/bundle/ruby/2.3.0/gems/compass-core-1.0.3/stylesheets/"
